# Generated by Django 5.1.5 on 2025-05-19 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cartegory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cartegory", models.CharField(max_length=100)),
                ("Created", models.DateTimeField(auto_now_add=True)),
                ("Modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="NewsContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=200)),
                ("Story", models.TextField()),
                ("Created", models.DateTimeField(auto_now_add=True)),
                ("Modified", models.DateTimeField(auto_now=True)),
                (
                    "Cartegory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="News.cartegory"
                    ),
                ),
                (
                    "Host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
