# Generated by Django 5.1.5 on 2025-05-19 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("News", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="newscontent",
            name="Picture",
            field=models.ImageField(blank=True, null=True, upload_to="News/"),
        ),
        migrations.CreateModel(
            name="LatestNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=200)),
                (
                    "Picture",
                    models.ImageField(blank=True, null=True, upload_to="News/"),
                ),
                ("Story", models.TextField()),
                ("Created", models.DateTimeField(auto_now_add=True)),
                ("Modified", models.DateTimeField(auto_now=True)),
                (
                    "Cartegory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="News.cartegory"
                    ),
                ),
                (
                    "Host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
