# Generated by Django 5.1.5 on 2025-05-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("News", "0002_newscontent_picture_latestnews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="latestnews",
            name="Picture",
            field=models.ImageField(blank=True, null=True, upload_to="News/Latest"),
        ),
        migrations.AlterField(
            model_name="newscontent",
            name="Picture",
            field=models.ImageField(blank=True, null=True, upload_to="News/Stories"),
        ),
    ]
